### ISSUE TITLE
NullPointerException after MaxMindGeoLocationService could not find country by IP

### ISSUE THREAD

**Issue by rmazurok** [prebid/prebid-server-java#1363]
NullPointerException while MaxMindGeo service could not identify country by IP
```
2021-07-08 13:39:45.795  INFO 1 --- [ntloop-thread-1] o.p.s.g.MaxMindGeoLocationService        : Request ip: 64.233.173.241
2021-07-08 13:39:45.796  INFO 1 --- [ntloop-thread-1] o.p.s.g.MaxMindGeoLocationService        : Request inetAddress: /64.233.173.241
2021-07-08 13:39:45.812  INFO 1 --- [ntloop-thread-1] o.p.s.g.MaxMindGeoLocationService        : Request city: com.maxmind.geoip2.model.CityResponse [ {"city":{},"continent":{"code":"AS","geoname_id":6255147,"names":{"de":"Asien","ru":"Азия","pt-BR":"Ásia","ja":"アジア","en":"Asia","fr":"Asie","zh-CN":"亚洲","es":"Asia"}},"country":{"is_in_european_union":false},"location":{"accuracy_radius":1000,"latitude":35.0,"longitude":105.0,"time_zone":"Australia/Perth"},"maxmind":{},"postal":{},"registered_country":{"geoname_id":6252001,"is_in_european_union":false,"iso_code":"US","names":{"de":"USA","ru":"США","pt-BR":"Estados Unidos","ja":"アメリカ合衆国","en":"United States","fr":"États-Unis","zh-CN":"美国","es":"Estados Unidos"}},"represented_country":{"is_in_european_union":false},"traits":{"ip_address":"64.233.173.241","is_anonymous":false,"is_anonymous_proxy":false,"is_anonymous_vpn":false,"is_hosting_provider":false,"is_legitimate_proxy":false,"is_public_proxy":false,"is_satellite_provider":false,"is_tor_exit_node":false}} ]
2021-07-08 13:39:45.816  INFO 1 --- [ntloop-thread-1] o.p.s.g.MaxMindGeoLocationService        : Request country: com.maxmind.geoip2.record.Country [ {"is_in_european_union":false} ]
2021-07-08 13:39:45.817  INFO 1 --- [ntloop-thread-1] o.p.s.g.MaxMindGeoLocationService        : Request isoCode: null
```
```
java.lang.NullPointerException
	at org.prebid.server.geolocation.MaxMindGeoLocationService.lookup(MaxMindGeoLocationService.java:71)
	at org.prebid.server.privacy.gdpr.TcfDefinerService.toTcfContext(TcfDefinerService.java:203)
	at org.prebid.server.privacy.gdpr.TcfDefinerService.resolveTcfContext(TcfDefinerService.java:88)
	at org.prebid.server.auction.PrivacyEnforcementService.contextFromBidRequest(PrivacyEnforcementService.java:99)
	at org.prebid.server.auction.AuctionRequestFactory.lambda$toAuctionContext$2(AuctionRequestFactory.java:202)

```

**Comment by rpanchyk** [comment]
Thank you, @rmazurok 
Fixed in #1366
Please feel free create new PR if any issues.
